# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaultDocker
  docker:
      - image: circleci/node:13.8.0
commands:
  print_pipeline_id:
    description: "Print workflow id"
    steps: 
      - run: echo $CIRCLE_WORKFLOW_ID
  print_value:
    description: "simple print param"
    parameters:
      value:
        type: string
        default: "hello"
    steps:
      - run: echo <<parameters.value>>
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    <<: *defaultDocker
    steps:
      - print_value:
          value: "hello"
      - print_pipeline_id
  save_hello_world_output:
    <<: *defaultDocker
    steps:
      - run: echo "hello" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    <<: *defaultDocker
    steps:
      - attach_workspace:
          at: ~/  
      - run: cat ~/output.txt       
  print_world:
    <<: *defaultDocker
    steps:
      - print_value:
          value: "world"
  print_name:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: 
          name: "echo an env var"
          command: |
            echo $NAME
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output      
      - print_name
