# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaultDocker
  docker:
      - image: circleci/node:13.8.0
commands:
  print_pipeline_id:
    description: "Print workflow id"
    steps: 
      - run: echo $CIRCLE_WORKFLOW_ID
  print_value:
    description: "simple print param"
    parameters:
      value:
        type: string
        default: "hello"
    steps:
      - run: echo <<parameters.value>>
# Orchestrate or schedule a set of jobs
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          command: |
            aws cloudformation deploy --template-file aws/template.yml --stack-name CircleStack
  install_application:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - 71:ec:08:3f:12:d7:12:b1:82:1d:26:c6:6e:8d:3f:85
      - run: 
          command: |
            ansible-playbook main-remote.yml -i ansible/inventory 
  print_hello:
    <<: *defaultDocker
    steps:
      - print_value:
          value: "hello"
      - print_pipeline_id
  save_hello_world_output:
    <<: *defaultDocker
    steps:
      - run: echo "hello" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    <<: *defaultDocker
    steps:
      - attach_workspace:
          at: ~/  
      - run: cat ~/output.txt       
  print_world:
    <<: *defaultDocker
    steps:
      - print_value:
          value: "world"
  print_name:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: 
          name: "echo an env var"
          command: |
            echo $NAME
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      #- create_infrastructure
      - install_application
      - print_hello
      - print_world:
          requires:
            - print_hello
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output      
      - print_name
